# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WV1oCj9Ezc6zKQiqogZAPjSUW7QatCRD
"""

from google.colab import files
files.upload()

import zipfile

with zipfile.ZipFile("Weather Dataset.zip", 'r') as zip_ref:
    zip_ref.extractall("data")

import os
print(os.listdir("data"))

print(os.listdir("data/Weather Dataset"))

import pandas as pd

df = pd.read_csv("data/Weather Dataset/weatherHistory.csv")
df.head()

print(df.columns)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df['Humidity_normalized'] = scaler.fit_transform(df[['Humidity']])

df[['Humidity', 'Humidity_normalized']].head()

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df['Temperature_normalized'] = scaler.fit_transform(df[['Temperature (C)']])

df[['Temperature (C)', 'Temperature_normalized']].head()