# -*- coding: utf-8 -*-
"""Day1_ex_XP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7SvyP0tblgp5aclmPaKHquYAuZA37-V
"""

#EX1

print('Hello world \n' *4)

#Ex2

print((99**3)*8)

#Ex3

#5 < 3  False
#3 == 3  True
#>>> 3 == "3" Error can't compare str and int
#"3" > 3 Error can't compare str and int
#"Hello" == "hello" False

#Ex4

computer_brand = 'Apple'
print(f"I have an {computer_brand} computer.")

#Ex5

name = 'Auriane'
age = 30
shoe_size = 8
info = 'I used to be a comedian in France'

print(f'My name is {name}, I am {age} years old and I wear a size {shoe_size}.')
print(f'An interesting thing about me is that {info}.')

#Ex6

a = 8
b = 7
if a>b:
  print('Hello World')

#Ex7

nbr = int(input('Enter a number: '))
if nbr%2==0:
  print('Your number is even.')
else:
  print('Your number is odd.')

#Ex8

name = input('What is your name ?')
if name=='Philippe':
  print(f'That is crazy! My dad is also named {name}! We have so much in common!')
else:
  print('Ok hopefully we will have something else in common...')

#Ex9

height = int(input('What is your height? (in cm) '))
if height>145:
  print('You are tall enough to ride!')
else:
  print('Sorry it seems you need to grow some more to ride!')