# -*- coding: utf-8 -*-
"""day1_pythonlessson.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqHxztMP43UekdG22m0hQco6CzqGT6Nw
"""

description = "strings are..."

description.upper()
description.replace('are','is')
description.replace(' are...','')

my_age = 30

print(my_age+123789)

bank_balance = '33000'
phone_number = 532287514

int(bank_balance)
str(phone_number)

first_name = 'Auriane'
last_name = 'Bouaziz'
print(first_name,last_name)

x = 5
y = 10
z = 0
word1 = "hello"
word2 = "world"

print(bool(x<y))
print(bool(y>z))
print(bool(word1!=word2))
print(bool(z))
print(bool(word1))

name='Alice'
age=30
city='New York'

print(f'Hello {name}! You are {age} years old and live in {city}.')

#Ask the user for their age using the input() function and store it in a variable age.
#Convert the inputted age into an integer and calculate the number of years until they turn 100.
#Display a message: "You will turn 100 in X years", where X is the number of years calculated.

age = int(input('Enter your age: '))
print(f'You will turn 100 in {100-age} years bhhh')

age = input("How old are you? ")
print(f"You are {age} years old")

name = input('What is your name? ')
if len(name)<5:
  print('You have a short name')

nbr = int(input('Enter a number: '))
if (nbr%3==0) and (nbr%5==0):
  print('FizzBuzz')
elif nbr%3==0:
  print('Fizz')
elif nbr%5==0:
  print('Buzz')
else:
  print('Number not divisible by 3 nor 5')

