# -*- coding: utf-8 -*-
"""titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186wJ15hge67EboNTUCT8hbmRtZliaQ00
"""

!pip install kaggle

import os

os.environ['KAGGLE_USERNAME'] = "Aurianedramy"
os.environ['KAGGLE_KEY'] = "KGAT_67d224ae4af576336bc5bef2c69b9327"

!kaggle datasets list

!kaggle datasets list

!kaggle datasets download -d yasserh/titanic-dataset



import zipfile

with zipfile.ZipFile("titanic-dataset.zip", "r") as zip_ref:
    zip_ref.extractall("titanic_data")

import os
print(os.listdir("titanic_data"))

import pandas as pd

df = pd.read_csv("titanic_data/Titanic-Dataset.csv")
df.head()

Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)

print(Q1)
print(Q3)
IQR = Q3 - Q1
print(IQR)

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(lower_bound)
print(upper_bound)

df = df[(df['Age'] >= lower_bound) & (df['Age'] <= upper_bound)]