# -*- coding: utf-8 -*-
"""week4day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1th2xI1_LJ0s8-c8AubQUCMN2C0shYvz6

EX1
# Write a short essay or report on the following topics:

# What is data analysis?
# Why is data analysis important in modern contexts?
# List and describe three areas where data analysis is applied today.
# Hint/Tip:

# Research current trends in data analysis and real-world examples to provide depth to your essay.

# My answer:
# Data analysis is the process of working with data to understand it and extract useful insights.
#  It involves collecting data, cleaning it, and then analyzing it to identify patterns or trends.
# The goal is to turn raw data into meaningful information that can help make better decisions.

# Today, data analysis is extremely important because we live in a world
# where a huge amount of data is generated every day. Without analysis, this data has no real value.
# Companies use data analysis to understand their customers, improve their products, and make smarter decisions.
# It also helps predict future trends and detect potential problems early.

# Data analysis is used in many different areas. For example, in healthcare,
#  it helps improve patient care and detect diseases earlier. In finance,
#  it is used to detect fraud and manage risks. In retail and e-commerce,
# companies analyze customer behavior to personalize offers and increase sales.

# In conclusion, data analysis has become essential in today’s world.
# It helps transform data into useful insights and allows organizations to be more efficient,
# competitive, and informed in their decisions.
"""

#EX2
# Objective: Practice dataset loading from Kaggle and initial analysis.
# Task:
# for the following dataset : How Much Sleep Do Americans Really Get?, Global Trends in Mental Health Disorder and Credit Card Approvals.

# Load the dataset into Jupyter or Google Colab.
# Display the first few rows.
# Provide a brief dataset description.

!pip install kaggle

import os
os.environ['KAGGLE_API_TOKEN'] = 'KGAT_a3a138e97aef1028d626956641c81743'

import pandas as pd

df = pd.read_csv("Time Americans Spend Sleeping.csv")
df.head()

"""#EX2
Dataset Description
This dataset contains information about the Time Americans Spend Sleeping. It includes the following columns:

Year: The year of data collection.
Period: The period of the data (e.g., Annual).
Avg hrs per day sleeping: The average hours per day spent sleeping.
Standard Error: The standard error associated with the average hours of sleep.
Type of Days: Indicates if the data is for 'All days' or specific types of days (e.g., 'Nonholiday weekdays').
Age Group: The age demographic for which the data is recorded (e.g., '15 years and over').
Activity: The activity being measured, which is 'Sleeping'.
Sex: The gender group for the data ('Both', 'Men', 'Women').
# The data appears to track average sleeping hours across different years, periods, age groups, and sexes.

#EX3
For the datasets from the previous exercise, categorize each column of it as either quantitative or qualitative and explain your reasoning.




Year: Quantitative. Represents a specific year, which is a numerical value that can be ordered and used for calculations (e.g., finding trends over time).
Period: Qualitative. Describes a time segment (e.g., 'Annual'), which is a categorical label.
Avg hrs per day sleeping: Quantitative. Represents the average number of hours, a measurable numerical value.
Standard Error: Quantitative. A numerical measure of the accuracy of the average hours of sleep.
Type of Days: Qualitative. Describes the type of days the data covers (e.g., 'All days', 'Nonholiday weekdays'), which are distinct categories.
Age Group: Qualitative. Describes demographic groups (e.g., '15 years and over'), which are categories even though they contain numbers.
Activity: Qualitative. Describes the activity being measured ('Sleeping'), which is a categorical label.
Sex: Qualitative. Describes the gender group ('Both', 'Men', 'Women'), which are distinct categories.
"""

#EX4
# Task:
# Load the Iris dataset using Kaggle into a Jupyter Notebook or Google Colaboratory Notebook.
# Identify and list which columns in your dataset are qualitative and which are quantitative.
# Write a brief description of why each column is classified as qualitative or quantitative.
# Tools: Jupyter Notebook, Python with Pandas library.

from google.colab import drive
drive.mount('/content/drive')

"""Based on the Iris dataset, here's the classification of columns into qualitative and quantitative:

Qualitative Column:

species: This column is qualitative because it represents the type or category of the iris flower (e.g., Iris-setosa, Iris-versicolor, Iris-virginica). It describes a characteristic rather than a numerical measurement. Quantitative Columns:

sepal_length: This column is quantitative as it measures the length of the sepal in a numerical format. It's a continuous variable. sepal_width: This column is quantitative as it measures the width of the sepal in a numerical format. It's a continuous variable. petal_length: This column is quantitative as it measures the length of the petal in a numerical format. It's a continuous variable. petal_width: This column is quantitative as it measures the width of the petal in a numerical format. It's a continuous variable. In essence, the quantitative columns represent physical measurements, while the qualitative column represents a categorical attribute.


"""

df1 = pd.read_csv("Iris_dataset.csv")
df1.head()

#EX5
# Task:
# Load the How Much Sleep Do Americans Really Get? dataset into Jupyter or Google Colab.
# Identify columns that could be interesting for a specific type of analysis (e.g., trend analysis, group comparison) and explain your choice.
# Tools: Jupyter Notebook, Python with Pandas library.

df.head()

"""#EX6 Identifying Interesting Columns for Analysis
Based on the Time Americans Spend Sleeping dataset, several columns could be useful for different types of analysis.
1. Trend Analysis


Year
This column is important to observe how sleeping habits change over time. By comparing the average sleeping hours from one year to another, we can identify trends or long-term changes in people’s sleep patterns.


Avg hrs per day sleeping
This is the main value we want to analyze. It shows the average number of hours people sleep per day and helps measure changes over the years or between groups.



2. Group Comparison


Age Group
This column allows us to compare sleeping habits between different age categories. For example, we can analyze whether younger or older people tend to sleep more.


Sex
Using this column, we can compare the average sleeping time between men and women and see if there are noticeable differences.


Type of Days
This column is useful to compare sleep duration depending on the type of day, such as weekdays or weekends. It can help show how routines influence sleep habits.


Period
This column indicates the reporting period of the data. In this dataset, it is mostly annual, so it may not provide a lot of variation, but it still gives context to the analysis.

EX7
For each of the following unstructured data sources, propose a method to convert it into structured data. Explain your reasoning.

A series of blog posts about travel experiences.
Audio recordings of customer service calls.
Handwritten notes from a brainstorming session.
A video tutorial on cooking.

A series of blog posts about travel experiences
A good method would be to use text analysis or manual tagging to extract key information such as destination, dates, activities, budget, and sentiment. This turns free text into organized categories that can be analyzed.
Audio recordings of customer service calls
The audio can first be transcribed into text using speech-to-text tools. Then, the text can be categorized by topic, customer issue, call duration, sentiment, and resolution status.
Handwritten notes from a brainstorming session
The notes can be scanned and converted into text using OCR. After that, the ideas can be organized into a table with categories such as idea, theme, priority, and responsible person.
A video tutorial on cooking
The video can be transcribed and analyzed to extract structured information such as recipe name, ingredients, quantities, cooking steps, preparation time, and difficulty level.
"""

#EX8
# Note: This dataset was originally sourced from Kaggle, but for easier access, it has been made available on GitHub.

# 👉 Please download the dataset directly from the GitHub repository to use it in this project.

# Import the train dataset. Use the train.csv file.
# Print the first few rows of the DataFrame.

df2 = pd.read_csv('train.csv')
df2.head()

#EX9
# Create a simple dataframe.
# Export the dataframe to an excel file.
# Export the dataframe to a JSON file.

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["Paris", "London", "New York"]
}

df3 = pd.DataFrame(data)

print(df3)

df3.to_excel('people.xlsx', sheet_name='Sheet1')

import os
print(os.listdir())

df3.to_json('people.json', orient='split')

import os
print(os.listdir())

#EX10
# Use a sample JSON dataset

# Import the JSON data from the provided URL.
# Use Pandas to read the JSON data.
# Display the first five entries of the data.
json_data = pd.read_json('https://jsonplaceholder.typicode.com/posts')
print(json_data.head())

