# -*- coding: utf-8 -*-
"""week4day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1th2xI1_LJ0s8-c8AubQUCMN2C0shYvz6

EX1
# Write a short essay or report on the following topics:

# What is data analysis?
# Why is data analysis important in modern contexts?
# List and describe three areas where data analysis is applied today.
# Hint/Tip:

# Research current trends in data analysis and real-world examples to provide depth to your essay.

# My answer:
# Data analysis is the process of working with data to understand it and extract useful insights.
#  It involves collecting data, cleaning it, and then analyzing it to identify patterns or trends.
# The goal is to turn raw data into meaningful information that can help make better decisions.

# Today, data analysis is extremely important because we live in a world
# where a huge amount of data is generated every day. Without analysis, this data has no real value.
# Companies use data analysis to understand their customers, improve their products, and make smarter decisions.
# It also helps predict future trends and detect potential problems early.

# Data analysis is used in many different areas. For example, in healthcare,
#  it helps improve patient care and detect diseases earlier. In finance,
#  it is used to detect fraud and manage risks. In retail and e-commerce,
# companies analyze customer behavior to personalize offers and increase sales.

# In conclusion, data analysis has become essential in today’s world.
# It helps transform data into useful insights and allows organizations to be more efficient,
# competitive, and informed in their decisions.
"""

#EX2
# Objective: Practice dataset loading from Kaggle and initial analysis.
# Task:
# for the following dataset : How Much Sleep Do Americans Really Get?, Global Trends in Mental Health Disorder and Credit Card Approvals.

# Load the dataset into Jupyter or Google Colab.
# Display the first few rows.
# Provide a brief dataset description.

!pip install kaggle

import os
os.environ['KAGGLE_API_TOKEN'] = 'KGAT_a3a138e97aef1028d626956641c81743'

import os
print(os.listdir())

import zipfile

with zipfile.ZipFile("How Much Sleep Do Americans.zip", 'r') as zip_ref:
    zip_ref.extractall("data")

print(os.listdir("data"))

print(os.listdir("data/How Much Sleep Do Americans"))

import pandas as pd

df = pd.read_csv("data/How Much Sleep Do Americans/Time Americans Spend Sleeping.csv")
df.head()

"""#EX2
Dataset Description
This dataset contains information about the Time Americans Spend Sleeping. It includes the following columns:

Year: The year of data collection.
Period: The period of the data (e.g., Annual).
Avg hrs per day sleeping: The average hours per day spent sleeping.
Standard Error: The standard error associated with the average hours of sleep.
Type of Days: Indicates if the data is for 'All days' or specific types of days (e.g., 'Nonholiday weekdays').
Age Group: The age demographic for which the data is recorded (e.g., '15 years and over').
Activity: The activity being measured, which is 'Sleeping'.
Sex: The gender group for the data ('Both', 'Men', 'Women').
# The data appears to track average sleeping hours across different years, periods, age groups, and sexes.

#EX3
For the datasets from the previous exercise, categorize each column of it as either quantitative or qualitative and explain your reasoning.




Year: Quantitative. Represents a specific year, which is a numerical value that can be ordered and used for calculations (e.g., finding trends over time).
Period: Qualitative. Describes a time segment (e.g., 'Annual'), which is a categorical label.
Avg hrs per day sleeping: Quantitative. Represents the average number of hours, a measurable numerical value.
Standard Error: Quantitative. A numerical measure of the accuracy of the average hours of sleep.
Type of Days: Qualitative. Describes the type of days the data covers (e.g., 'All days', 'Nonholiday weekdays'), which are distinct categories.
Age Group: Qualitative. Describes demographic groups (e.g., '15 years and over'), which are categories even though they contain numbers.
Activity: Qualitative. Describes the activity being measured ('Sleeping'), which is a categorical label.
Sex: Qualitative. Describes the gender group ('Both', 'Men', 'Women'), which are distinct categories.
"""

