# -*- coding: utf-8 -*-
"""week4day4xp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ueYcAMl71g4ZFjrFk5owLJYCUrdP-YD7
"""

#EX4
# Task:
# Load the Iris dataset using Kaggle into a Jupyter Notebook or Google Colaboratory Notebook.
# Identify and list which columns in your dataset are qualitative and which are quantitative.
# Write a brief description of why each column is classified as qualitative or quantitative.
# Tools: Jupyter Notebook, Python with Pandas library.

!pip install kaggle

import os
os.environ['KAGGLE_API_TOKEN'] = 'KGAT_a3a138e97aef1028d626956641c81743'

from google.colab import drive
drive.mount('/content/drive')

"""Based on the Iris dataset, here's the classification of columns into qualitative and quantitative:

Qualitative Column:

species: This column is qualitative because it represents the type or category of the iris flower (e.g., Iris-setosa, Iris-versicolor, Iris-virginica). It describes a characteristic rather than a numerical measurement.
Quantitative Columns:

sepal_length: This column is quantitative as it measures the length of the sepal in a numerical format. It's a continuous variable.
sepal_width: This column is quantitative as it measures the width of the sepal in a numerical format. It's a continuous variable.
petal_length: This column is quantitative as it measures the length of the petal in a numerical format. It's a continuous variable.
petal_width: This column is quantitative as it measures the width of the petal in a numerical format. It's a continuous variable.
In essence, the quantitative columns represent physical measurements, while the qualitative column represents a categorical attribute.
"""

df.head()

#EX5
# Task:
# Load the How Much Sleep Do Americans Really Get? dataset into Jupyter or Google Colab.
# Identify columns that could be interesting for a specific type of analysis (e.g., trend analysis, group comparison) and explain your choice.
# Tools: Jupyter Notebook, Python with Pandas library.

import os
print(os.listdir('/content/drive/MyDrive/Colab Notebooks'))

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Time Americans Spend Sleeping.csv')
df.head()

"""Identifying Interesting Columns for Analysis
Based on the Time Americans Spend Sleeping dataset, several columns could be useful for different types of analysis.
1. Trend Analysis


Year
This column is important to observe how sleeping habits change over time. By comparing the average sleeping hours from one year to another, we can identify trends or long-term changes in people’s sleep patterns.


Avg hrs per day sleeping
This is the main value we want to analyze. It shows the average number of hours people sleep per day and helps measure changes over the years or between groups.



2. Group Comparison


Age Group
This column allows us to compare sleeping habits between different age categories. For example, we can analyze whether younger or older people tend to sleep more.


Sex
Using this column, we can compare the average sleeping time between men and women and see if there are noticeable differences.


Type of Days
This column is useful to compare sleep duration depending on the type of day, such as weekdays or weekends. It can help show how routines influence sleep habits.


Period
This column indicates the reporting period of the data. In this dataset, it is mostly annual, so it may not provide a lot of variation, but it still gives context to the analysis.

EX6
Below are various data sources. Identify whether each one is an example of structured or unstructured data.

A company’s financial reports stored in an Excel file.
Photographs uploaded to a social media platform.
A collection of news articles on a website.
Inventory data in a relational database.
Recorded interviews from a market research study.

A company’s financial reports stored in an Excel file
→ Structured data
Because the information is organized in rows and columns with a clear format.
Photographs uploaded to a social media platform
→ Unstructured data
Because images do not follow a predefined table or organized structure.
A collection of news articles on a website
→ Unstructured data
Because the content is mainly free text and does not have a fixed structure.
Inventory data in a relational database
→ Structured data
Because the data is stored in tables with organized fields and relationships.
Recorded interviews from a market research study
→ Unstructured data
Because audio recordings are not organized in a predefined format and usually require transcription or processing before analysis.

EX7
For each of the following unstructured data sources, propose a method to convert it into structured data. Explain your reasoning.

A series of blog posts about travel experiences.
Audio recordings of customer service calls.
Handwritten notes from a brainstorming session.
A video tutorial on cooking.

A series of blog posts about travel experiences
A good method would be to use text analysis or manual tagging to extract key information such as destination, dates, activities, budget, and sentiment. This turns free text into organized categories that can be analyzed.
Audio recordings of customer service calls
The audio can first be transcribed into text using speech-to-text tools. Then, the text can be categorized by topic, customer issue, call duration, sentiment, and resolution status.
Handwritten notes from a brainstorming session
The notes can be scanned and converted into text using OCR. After that, the ideas can be organized into a table with categories such as idea, theme, priority, and responsible person.
A video tutorial on cooking
The video can be transcribed and analyzed to extract structured information such as recipe name, ingredients, quantities, cooking steps, preparation time, and difficulty level.
"""

#EX8
# Note: This dataset was originally sourced from Kaggle, but for easier access, it has been made available on GitHub.

# 👉 Please download the dataset directly from the GitHub repository to use it in this project.

# Import the train dataset. Use the train.csv file.
# Print the first few rows of the DataFrame.

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train.csv')
df.head()

