# -*- coding: utf-8 -*-
"""week4day4xp9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nL2LtIOD5dxpclu1wOxxTWZtrK3yhjiY
"""

#EX9
# Create a simple dataframe.
# Export the dataframe to an excel file.
# Export the dataframe to a JSON file.

import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["Paris", "London", "New York"]
}

df = pd.DataFrame(data)

print(df)

df.to_excel('people.xlsx', sheet_name='Sheet1')

import os
print(os.listdir())

df.to_json('people.json', orient='split')

import os
print(os.listdir())

#EX10
# Use a sample JSON dataset

# Import the JSON data from the provided URL.
# Use Pandas to read the JSON data.
# Display the first five entries of the data.
json_data = pd.read_json('https://jsonplaceholder.typicode.com/posts')
print(json_data.head())

