# -*- coding: utf-8 -*-
"""week5day2xp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zm6i9PVhFWGtg9M2pFWEoyXIYDW_k25N
"""

#EX1
# 🌟 Exercise 1: Basic Usage of SciPy
# Task: Import the SciPy library and explore its version.

import scipy

print(scipy.__version__)

# #EX2
#   Exercise 2: Descriptive Statistics
# Task: Given a sample dataset, calculate the mean, median, variance, and standard deviation using SciPy.
# Sample Dataset:
# data = [12, 15, 13, 12, 18, 20, 22, 21]

import numpy as np
from scipy import stats

data = [12, 15, 13, 12, 18, 20, 22, 21]

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

# 🌟 Exercise 3: Understanding Distributions
# Task: Generate a normal distribution using SciPy with a mean of 50 and a standard deviation of 10. Plot this distribution.
# Code Example:
# import numpy as np
# import matplotlib.pyplot as plt
# from scipy.stats import norm

# # complete your code here

import matplotlib.pyplot as plt
from scipy.stats import norm

mean = 50
std_dev = 10

x = np.linspace(mean - 4 * std_dev, mean + 4 * std_dev, 1000)
y = norm.pdf(x, mean, std_dev)

plt.plot(x, y)
plt.title("Normal Distribution: mean = 50, standard deviation = 10")
plt.xlabel("x")
plt.ylabel("Probability density")
plt.grid(True)
plt.show()

#EX4
# 🌟 Exercise 4: T-Test Application
# Task: Perform a T-test on two sets of randomly generated data.
# Code Example:
# data1 = np.random.normal(50, 10, 100)
# data2 = np.random.normal(60, 10, 100)

# # complete your code here

from scipy import stats

data1 = np.random.normal(50, 10, 100)
data2 = np.random.normal(60, 10, 100)

t_statistic, p_value = stats.ttest_ind(data1, data2)

print("T-statistic:", t_statistic)
print("P-value:", p_value)

#EX5
# 🌟 Exercise 5: Linear Regression Analysis
# Objective: Apply linear regression to a dataset and interpret the results.

# Task: Given a dataset of housing prices (house_prices) and their corresponding sizes (house_sizes), use linear regression to predict the price of a house given its size.
# Dataset:
# house_sizes: [50, 70, 80, 100, 120] (in square meters)
# house_prices: [150,000, 200,000, 210,000, 250,000, 280,000] (in currency units)
# Questions:
# What is the slope and intercept of the regression line?
# Predict the price of a house that is 90 square meters.
# Interpret the meaning of the slope in the context of housing prices.


house_sizes = np.array([50, 70, 80, 100, 120])
house_prices = np.array([150000, 200000, 210000, 250000, 280000])

slope, intercept, r_value, p_value, std_err = stats.linregress(
    house_sizes,
    house_prices
)

predicted_price_90 = slope * 90 + intercept

print("Slope:", slope)
print("Intercept:", intercept)
print("Predicted price for 90 m²:", predicted_price_90)
print("R-squared:", r_value ** 2)

size_to_predict = 90
predicted_price = slope * size_to_predict + intercept

print("Predicted price for 90 m²:", predicted_price)

# The predicted price for a 90 square meter house is approximately 228,973 currency units.
# The slope is approximately 1828.77, which means that each additional square meter is associated with an average increase of about 1,829 currency units in the predicted house price.

# #EX6
# 🌟 Exercise 6: Understanding ANOVA
# Objective: Test understanding of ANOVA and its application.

# Task: Three different fertilizers are applied to three separate groups of plants to test their effectiveness.
# The growth in centimeters is recorded.
# Dataset:
# fertilizer_1: [5, 6, 7, 6, 5]
# fertilizer_2: [7, 8, 7, 9, 8]
# fertilizer_3: [4, 5, 4, 3, 4]
# Questions:
# Perform an ANOVA test on the given data. What are the F-value and P-value?
# Based on the P-value, do the fertilizers have significantly different effects on plant growth?
# Explain what would happen if the P-value were greater than 0.05.



fertilizer_1 = [5, 6, 7, 6, 5]
fertilizer_2 = [7, 8, 7, 9, 8]
fertilizer_3 = [4, 5, 4, 3, 4]

f_value, p_value = stats.f_oneway(
    fertilizer_1,
    fertilizer_2,
    fertilizer_3
)

print("F-value:", f_value)
print("P-value:", p_value)

alpha = 0.05

if p_value < alpha:
    print("The fertilizers have significantly different effects on plant growth.")
else:
    print("There is not enough evidence to say that the fertilizers have significantly different effects.")

# The ANOVA test gives an F-value of approximately 28.53 and a P-value of approximately 0.0000275.

# Since the P-value is less than 0.05, we reject the null hypothesis.
#  This means that the fertilizers have significantly different effects on plant growth.

# If the P-value were greater than 0.05, we would fail to reject the null hypothesis.
# In that case, there would not be enough statistical evidence to say that the fertilizers have different effects on plant growth.