# -*- coding: utf-8 -*-
"""week4day6xp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aYeN9R4hHkmHtV8eOc7uNv_dmt1XYJNK
"""

#EX1
# Instructions
# Objective: Identify and remove duplicate entries in the Titanic dataset.

# Load the Titanic dataset.
# Identify if there are any duplicate rows based on all columns.
# Remove any duplicate rows found in the dataset.
# Verify the removal of duplicates by checking the number of rows before and after the duplicate removal.
# Hint: Use the duplicated() and drop_duplicates() functions in Pandas.

import pandas as pd

df = pd.read_csv("train.csv")

print("Nbr of rows:", len(df))

print("Nbr of duplicates :", df.duplicated().sum())

df = df.drop_duplicates()

print("Nbr of rows after :", len(df))

#EX2
# Instructions
# Identify columns in the Titanic dataset with missing values.
# Explore different strategies for handling missing data, such as removal, imputation, and filling with a constant value.
# Apply each strategy to different columns based on the nature of the data.
# Hint: Review methods like dropna(), fillna(), and SimpleImputer from scikit-learn.



# Voir les colonnes avec des valeurs manquantes
print(df.isnull().sum())

# Exemple 1 : supprimer les lignes qui ont une valeur manquante
df_without_missing_rows = df.dropna()

print("Nombre de lignes avant :", len(df))
print("Nombre de lignes après suppression des lignes vides :", len(df_without_missing_rows))

# Exemple 2 : remplacer les âges manquants par la moyenne des âges
df_age_filled = df.copy()
df_age_filled["Age"] = df_age_filled["Age"].fillna(df["Age"].mean())

# Exemple 3 : remplacer les cabines manquantes par "Unknown"
df_cabin_filled = df.copy()
df_cabin_filled["Cabin"] = df_cabin_filled["Cabin"].fillna("Unknown")

#EX3
# Instructions
# Create new features, such as Family Size from SibSp and Parch, and Title extracted from the Name column.
# Convert categorical variables into numerical form using techniques like one-hot encoding or label encoding.
# You will encode new categorical features (like Title) here, but do not scale numerical features yet —
# that will come after outlier handling.
# Hint: Utilize Pandas for data manipulation and scikit-learn’s preprocessing module for encoding.

df["FamilySize"] = df["SibSp"] + df["Parch"] + 1

df[["SibSp", "Parch", "FamilySize"]].head()

# Extract Title from Name
df["Title"] = df["Name"].str.extract(r" ([A-Za-z]+)\.", expand=False)

# Convert Title into numbers
# Title is a categorical column because it contains text categories.
# We convert it into numbers using label encoding.
df["Title_Code"] = df["Title"].astype("category").cat.codes

# Display the result
df[["Name", "SibSp", "Parch", "FamilySize", "Title", "Title_Code"]].head()

import matplotlib.pyplot as plt
import numpy as np

# 1. Look at Fare and Age
print(df[["Fare", "Age"]].describe())

# 2. Visualize Fare
df["Fare"].hist()
plt.title("Distribution of Fare")
plt.xlabel("Fare")
plt.ylabel("Number of passengers")
plt.show()

df.boxplot(column="Fare")
plt.title("Boxplot of Fare")
plt.show()

# 3. Detect outliers in Fare with IQR
Q1 = df["Fare"].quantile(0.25)
Q3 = df["Fare"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

fare_outliers = df[df["Fare"] > upper_limit]

print("Upper limit for Fare:", upper_limit)
print("Number of Fare outliers:", len(fare_outliers))

# 4. Quantile capping
df_capped = df.copy()

fare_cap = df_capped["Fare"].quantile(0.98)
df_capped["Fare"] = df_capped["Fare"].clip(upper=fare_cap)

print("Maximum Fare before:", df["Fare"].max())
print("Maximum Fare after capping:", df_capped["Fare"].max())

# 5. Log transformation
df_log = df.copy()
df_log["Fare_Log"] = np.log1p(df_log["Fare"])

# 6. Row removal
df_removed = df[df["Fare"] <= fare_cap]

print("Rows before:", len(df))
print("Rows after removing high Fare values:", len(df_removed))

# 1. Look at Age
print(df["Age"].describe())

# 2. Visualize Age
df["Age"].hist()
plt.title("Distribution of Age")
plt.xlabel("Age")
plt.ylabel("Number of passengers")
plt.show()

df.boxplot(column="Age")
plt.title("Boxplot of Age")
plt.show()

# 3. Detect outliers in Age with IQR
Q1_age = df["Age"].quantile(0.25)
Q3_age = df["Age"].quantile(0.75)

IQR_age = Q3_age - Q1_age

lower_limit_age = Q1_age - 1.5 * IQR_age
upper_limit_age = Q3_age + 1.5 * IQR_age

age_outliers = df[(df["Age"] < lower_limit_age) | (df["Age"] > upper_limit_age)]

print("Lower limit for Age:", lower_limit_age)
print("Upper limit for Age:", upper_limit_age)
print("Number of Age outliers:", len(age_outliers))

# 4. Quantile capping
df_age_capped = df.copy()

age_lower_cap = df_age_capped["Age"].quantile(0.02)
age_upper_cap = df_age_capped["Age"].quantile(0.98)

df_age_capped["Age"] = df_age_capped["Age"].clip(
    lower=age_lower_cap,
    upper=age_upper_cap
)

print("Minimum Age before:", df["Age"].min())
print("Maximum Age before:", df["Age"].max())

print("Minimum Age after capping:", df_age_capped["Age"].min())
print("Maximum Age after capping:", df_age_capped["Age"].max())

# 5. Log transformation
df_age_log = df.copy()
df_age_log["Age_Log"] = np.log1p(df_age_log["Age"])

# 6. Row removal
df_age_removed = df[
    (df["Age"] >= age_lower_cap) &
    (df["Age"] <= age_upper_cap)
]

print("Rows before:", len(df))
print("Rows after removing Age outliers:", len(df_age_removed))

#EX6
# Goal: Finalize categorical variable encoding.
# 1. Identify remaining categorical columns (e.g. Sex, Embarked, Title).
# 2. Apply:
# One-Hot Encoding for nominal variables.
# Label Encoding if any ordinal variables remain.
# 3. Merge encoded columns back into the main dataset.
# 📌 Reminder: Encoding comes after handling missing values and outliers, but before scaling (if applicable).

# 1. Check categorical columns
print(df_scaled[["Sex", "Embarked", "Title"]].head())

# 2. One-hot encoding for categorical columns
df_encoded = pd.get_dummies(
    df_scaled,
    columns=["Sex", "Embarked", "Title"],
    drop_first=True
)

# 3. Display result
df_encoded.head()

# I identified the remaining categorical columns: Sex, Embarked, and Title.
# I used one-hot encoding with pd.get_dummies() to convert these text columns into numerical columns.
# The encoded columns were merged back into the dataset automatically in df_encoded.

# 🌟 Exercise 5: Data Standardization and Normalization
# Goal: Scale numerical features to prepare for modeling.

# Use StandardScaler (mean = 0, std = 1) for normally distributed features.
# Use MinMaxScaler (range [0, 1]) for features that are skewed or bounded.
# 📌 Important: Perform this step after outlier treatment to avoid distortion caused by extreme values.

from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Create a copy of the dataset
df_scaled = df.copy()

# 1. Cap outliers before scaling

# Fare capping
fare_cap = df_scaled["Fare"].quantile(0.98)
df_scaled["Fare"] = df_scaled["Fare"].clip(upper=fare_cap)

# Age capping
age_lower_cap = df_scaled["Age"].quantile(0.02)
age_upper_cap = df_scaled["Age"].quantile(0.98)

df_scaled["Age"] = df_scaled["Age"].clip(
    lower=age_lower_cap,
    upper=age_upper_cap
)

# 2. Standardize Age
standard_scaler = StandardScaler()

df_scaled["Age_Standardized"] = standard_scaler.fit_transform(df_scaled[["Age"]])

# 3. Normalize Fare
minmax_scaler = MinMaxScaler()

df_scaled["Fare_Normalized"] = minmax_scaler.fit_transform(df_scaled[["Fare"]])

# Display result
df_scaled[["Age", "Age_Standardized", "Fare", "Fare_Normalized"]].head()

# I scaled the numerical features after outlier treatment.
# Age was standardized using StandardScaler, and Fare was normalized using MinMaxScaler.

# 🌟 Exercise 7: Data Transformation for Age Feature
# Goal: Create and encode age groups.

# Use pd.cut() to create bins for life stages (e.g. child, teen, adult, senior).
# Apply one-hot encoding using pd.get_dummies().
# 📌 Example: You might define bins like [0, 12, 18, 60, 100] and label them accordingly.


# 1. Create age groups
age_bins = [0, 12, 18, 60, 100]
age_labels = ["child", "teen", "adult", "senior"]

df_encoded["AgeGroup"] = pd.cut(
    df_encoded["Age"],
    bins=age_bins,
    labels=age_labels
)

# 2. One-hot encode AgeGroup
df_encoded = pd.get_dummies(
    df_encoded,
    columns=["AgeGroup"],
    drop_first=True
)

# 3. Display result
df_encoded.head()