# -*- coding: utf-8 -*-
"""dailyweek5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHLepcKDvuV-FgYicBTdryNtRPaN9jFf
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("US Superstore data.xls")

df.head()

df.shape

df.info()

# Check duplicate rows
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

# There are no duplicate rows in the dataset, so no duplicate removal is needed.

df[["Sales", "Quantity", "Discount", "Profit"]].describe()

print("Negative Sales:", len(df[df["Sales"] < 0]))
print("Quantity less than 1:", len(df[df["Quantity"] < 1]))
print("Discount less than 0:", len(df[df["Discount"] < 0]))
print("Discount greater than 1:", len(df[df["Discount"] > 1]))

# The numerical columns Sales, Quantity and Discount do not contain invalid values.
# Sales is never negative, Quantity is always at least 1, and Discount is always between 0 and 1.
# Profit can be negative because it represents a loss, so negative Profit values are not necessarily errors.

# Create date-related columns
df["Order Year"] = df["Order Date"].dt.year
df["Order Month"] = df["Order Date"].dt.month
df["Order Month-Year"] = df["Order Date"].dt.to_period("M")

# Create shipping time column
df["Shipping Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

df[["Order Date", "Ship Date", "Order Year", "Order Month", "Order Month-Year", "Shipping Days"]].head()

df["Shipping Days"].describe()

# Shipping Days ranges from 0 to 7 days, with an average of about 4 days.
# There are no negative shipping times, so the order and shipping dates are consistent.

# Final preprocessing check
print("Final shape:", df.shape)
df.head()

df["Country"].unique()
# The dataset contains only one country, United States. Therefore, a country-level map is limited. A state-level map would provide more useful insights.

# Profit Margin tells us how profitable the sales are
df["Profit Margin"] = df["Profit"] / df["Sales"]

print("Rows with Sales = 0:", len(df[df["Sales"] == 0]))

# 1. Which States Have The Most Sales?
state_sales = df.groupby("State")["Sales"].sum().sort_values(ascending=False)

state_sales.head(10)

import matplotlib.pyplot as plt

state_sales.head(10).plot(kind="bar")

plt.title("Top 10 States by Sales")
plt.xlabel("State")
plt.ylabel("Total Sales")
plt.show()

# The chart shows the top 10 states by total sales.
# California has the highest sales, followed by other large markets such as New York and Texas.

# 2. Difference Between New York And California
ny_ca = df[df["State"].isin(["New York", "California"])]

ny_ca_summary = ny_ca.groupby("State")[["Sales", "Profit"]].sum()

ny_ca_summary

ny_ca_summary.plot(kind="bar")

plt.title("Sales and Profit: New York vs California")
plt.xlabel("State")
plt.ylabel("Amount")
plt.show()

# California generates higher total sales and profit than New York.
# Both states are important markets, but California appears to be the stronger market overall.

# 3. Who Is An Outstanding Customer In New York?
ny_customers = df[df["State"] == "New York"].groupby("Customer Name").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Num_Orders=("Order ID", "nunique")
).sort_values("Total_Sales", ascending=False)

top_ny_sales = ny_customers.head(10).reset_index()

plt.figure(figsize=(10, 6))

sns.barplot(
    data=top_ny_sales,
    x="Total_Sales",
    y="Customer Name"
)

plt.title("Top 10 Customers in New York by Sales")
plt.xlabel("Total Sales")
plt.ylabel("Customer Name")
plt.show()

# The horizontal bar chart makes it easier to read customer names.
# The chart shows the top customers by sales.
# The top customer in New York by sales is the customer with the highest total sales value: Tom Ashbrook.
# I grouped New York customers by customer name and calculated total sales, total profit, and number of orders.
# A high-sales customer is important for revenue, but this does not always mean they are the most profitable.

top_ny_profit = ny_customers.sort_values("Total_Profit", ascending=False).head(10).reset_index()

plt.figure(figsize=(10, 6))

sns.barplot(
    data=top_ny_profit,
    x="Total_Profit",
    y="Customer Name"
)

plt.title("Top 10 Customers in New York by Profit")
plt.xlabel("Total Profit")
plt.ylabel("Customer Name")
plt.show()

# This chart shows the top 10 customers in New York by total profit.
# The most outstanding customer by profit is the customer with the highest profit value, Tom Ashbrook,
# which may be more important for business performance than sales alone but in that case, it is the same than sales.

# Question 4 — Are there differences among states in profitability?
sstate_profit = df.groupby("State")["Profit"].sum().sort_values(ascending=False)

plt.figure(figsize=(16, 8))

colors = ["#2ecc71" if value >= 0 else "#e74c3c" for value in state_profit.values]

state_profit.plot(
    kind="bar",
    color=colors,
    edgecolor="black"
)

plt.title("Total Profit by State")
plt.xlabel("State")
plt.ylabel("Total Profit")
plt.axhline(y=0, color="black", linewidth=1)
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

# I grouped the data by state and calculated total profit for each state.
#  Green bars represent profitable states, while red bars represent states with negative profit.
#  The chart shows that profitability varies strongly across states.

# Q5 — Pareto Principle: Customers And Profit
import numpy as np

customer_profit = (
    df.groupby("Customer Name")["Profit"]
    .sum()
    .sort_values(ascending=False)
)

profitable_customers = customer_profit[customer_profit > 0]

total_positive_profit = profitable_customers.sum()

cumulative_profit = profitable_customers.cumsum() / total_positive_profit * 100

customer_percentage = (
    np.arange(1, len(profitable_customers) + 1)
    / len(profitable_customers) * 100
)

plt.figure(figsize=(12, 7))

plt.plot(
    customer_percentage,
    cumulative_profit.values,
    color="#3498db",
    linewidth=2
)

plt.axhline(y=80, color="red", linestyle="--", label="80% of Profit")
plt.axvline(x=20, color="orange", linestyle="--", label="20% of Customers")

plt.title("Pareto Analysis: Customers and Profit")
plt.xlabel("Percentage of Profitable Customers")
plt.ylabel("Cumulative Profit (%)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

# The graph gives a visual indication of whether the Pareto principle applies.
# However, the numerical check confirms the result more precisely.

top_20_count = int(np.ceil(len(profitable_customers) * 0.20))

top_20_profit = profitable_customers.head(top_20_count).sum()
top_20_profit_percentage = top_20_profit / total_positive_profit * 100

print("Top 20% profitable customers contribute to", round(top_20_profit_percentage, 1), "% of positive profit")

# Q6 — Top 20 Cities By Sales And Profit
city_stats = df.groupby("City").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum")
).reset_index()

city_stats["Profit_Margin_%"] = (
    city_stats["Total_Profit"] / city_stats["Total_Sales"] * 100
).round(2)

top20_sales = city_stats.nlargest(20, "Total_Sales")
top20_profit = city_stats.nlargest(20, "Total_Profit")

fig, axes = plt.subplots(1, 2, figsize=(18, 8))

axes[0].barh(top20_sales["City"], top20_sales["Total_Sales"], color="#3498db")
axes[0].set_title("Top 20 Cities by Sales")
axes[0].set_xlabel("Total Sales")
axes[0].invert_yaxis()

colors = ["#2ecc71" if value >= 0 else "#e74c3c" for value in top20_profit["Total_Profit"]]

axes[1].barh(top20_profit["City"], top20_profit["Total_Profit"], color=colors)
axes[1].set_title("Top 20 Cities by Profit")
axes[1].set_xlabel("Total Profit")
axes[1].invert_yaxis()

plt.tight_layout()
plt.show()

# # I compared the top 20 cities by sales and by profit.
# The cities with the highest sales are not always the cities with the highest profit.
# This means that revenue and profitability should be analyzed separately.

# Q7 — Top 20 Customers By Sales
top20_customers_sales = (
    df.groupby("Customer Name")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(20)
)

plt.figure(figsize=(10, 8))

sns.barplot(
    x=top20_customers_sales.values,
    y=top20_customers_sales.index
)

plt.title("Top 20 Customers by Sales")
plt.xlabel("Total Sales")
plt.ylabel("Customer Name")
plt.show()

# Q8 — Cumulative Sales Curve / Pareto Sales
customer_sales = (
    df.groupby("Customer Name")["Sales"]
    .sum()
    .sort_values(ascending=False)
)

total_sales = customer_sales.sum()
cumulative_sales = customer_sales.cumsum() / total_sales * 100

customer_percentage = (
    np.arange(1, len(customer_sales) + 1)
    / len(customer_sales) * 100
)

plt.figure(figsize=(12, 7))

plt.plot(customer_percentage, cumulative_sales.values, linewidth=2)

plt.axhline(y=80, color="red", linestyle="--", label="80% of Sales")
plt.axvline(x=20, color="orange", linestyle="--", label="20% of Customers")

plt.title("Cumulative Sales Curve by Customers")
plt.xlabel("Percentage of Customers")
plt.ylabel("Cumulative Sales (%)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

top_20_count = int(np.ceil(len(customer_sales) * 0.20))

top_20_sales = customer_sales.head(top_20_count).sum()
top_20_sales_percentage = top_20_sales / total_sales * 100

print("Top 20% customers contribute to", round(top_20_sales_percentage, 1), "% of total sales")

# The Pareto principle does not strictly apply to sales,
# because the top 20% of customers generate much less than 80% of total sales.

# Q9 — Marketing Strategy Decisions
state_full = df.groupby("State").agg(
    Total_Sales=("Sales", "sum"),
    Total_Profit=("Profit", "sum"),
    Num_Orders=("Order ID", "nunique"),
    Num_Customers=("Customer ID", "nunique")
)

state_full["Profit_Margin_%"] = (
    state_full["Total_Profit"] / state_full["Total_Sales"] * 100
).round(2)

state_full["Avg_Order_Value"] = (
    state_full["Total_Sales"] / state_full["Num_Orders"]
).round(2)

plt.figure(figsize=(14, 8))

scatter = plt.scatter(
    state_full["Total_Sales"],
    state_full["Total_Profit"],
    s=state_full["Num_Customers"] * 5,
    c=state_full["Profit_Margin_%"],
    cmap="RdYlGn",
    alpha=0.6,
    edgecolor="black"
)

plt.colorbar(scatter, label="Profit Margin (%)")
plt.axhline(y=0, color="red", linestyle="--")

plt.xlabel("Total Sales")
plt.ylabel("Total Profit")
plt.title("States: Sales vs Profit")

for state in ["California", "New York", "Texas", "Washington", "Pennsylvania"]:
    if state in state_full.index:
        row = state_full.loc[state]
        plt.annotate(
            state,
            (row["Total_Sales"], row["Total_Profit"]),
            fontsize=9,
            fontweight="bold"
        )

plt.tight_layout()
plt.show()

# Based on the analysis, marketing should prioritize states and cities with both high sales and high profit.
# High-sales but low-profit areas should be reviewed carefully,
# especially if discounts are reducing profitability.
# Customers with high sales or high profit should be targeted with loyalty programs and personalized offers.