# -*- coding: utf-8 -*-
"""day4_ex_xp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vO-_boWiRB4APNb8BqApWy2CDPmweVP9
"""

#EX1
#Create a set called my_fav_numbers and populate it with your favorite numbers.
#Add two new numbers to the set.
#Remove the last number you added to the set.
#Create another set called friend_fav_numbers and populate it with your friend’s favorite numbers.
#Concatenate my_fav_numbers and friend_fav_numbers to create a new set called our_fav_numbers.
#Note: Sets are unordered collections, so ensure no duplicate numbers are added.


my_fav_numbers = set()

my_fav_numbers = {4,5,8,12,7}

my_fav_numbers.add(11)
my_fav_numbers.add(33)

my_fav_numbers.remove(33)

friend_fav_numbers = set()

friend_fav_numbers = {1,6,9,14}

our_fav_numbers = my_fav_numbers.union(friend_fav_numbers)

print(our_fav_numbers)

#EX2
#Given a tuple of integers, try to add more integers to the tuple.
#Hint: Tuples are immutable, meaning they cannot be changed after creation.
#Think about why you can’t add more integers to a tuple.

#Tuples are immutable lists, which means items can’t be changed. so impossible to add element to it.

#EX3
# You have a list: basket = ["Banana", "Apples", "Oranges", "Blueberries"]
# Remove "Banana" from the list.
# Remove "Blueberries" from the list.
# Add "Kiwi" to the end of the list.
# Add "Apples" to the beginning of the list.
# Count how many times "Apples" appear in the list.
# Empty the list.
# Print the final state of the list.

basket = ["Banana", "Apples", "Oranges", "Blueberries"]
basket.remove("Banana")
basket.remove("Blueberries")
basket.append("Kiwi")
basket.insert(0,"Apples")
print(basket.count("Apples"))  #added a print to check the count result
basket.clear()
print(basket)

#EX4
# Recap: What is a float? What’s the difference between a float and an integer?
# Create a list containing the following sequence of mixed types: floats and integers:
# 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5.
# Avoid hard-coding each number manually.
# Think: Can you generate this sequence using a loop or another method?

#A float is when a rational number ends with a decimal figure. While integers represent whole numbers from negative infinity to infinity.

#flo_list = [1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]

flo_list = []
for i in range(3,11):
    flo_list.append(i / 2)
print(flo_list)

#EX5
# Write a for loop to print all numbers from 1 to 20, inclusive.
# Write another for loop that prints every number from 1 to 20 where the index is even.

for i in range(1,21):
  print(i)

for i in range(1,21,2):
  print(i)

#EX6
# Use an input to ask the user to enter their name.
# Using a while True loop, check if the user gave a proper name (not digits and at least 3 letters long)
# hint: check for the method isdigit()
# if the input is incorrect, keep asking for the correct input until it is correct
# if the input is correct print “thank you” and break the loop

name = input('Enter your name: ')
while len(name)<3 or name.isalpha()==False:
  name = input("Improper input, please try again: ")

print("Thank you")

#EX7
# Ask the user to input their favorite fruits (they can input several fruits, separated by spaces).
# Store these fruits in a list.
# Ask the user to input the name of any fruit.
# If the fruit is in their list of favorite fruits, print:
# "You chose one of your favorite fruits! Enjoy!"
# If not, print:
# "You chose a new fruit. I hope you enjoy it!"


fav_fruits = input("Enter your favorite fruits: ").lower()
fav_fruit_list  = fav_fruits.split()
fruit = input("Enter the name of a fruit: ").strip().lower()
if fruit in fav_fruit_list:
  print("You chose one of your favorite fruits! Enjoy!")
else:
  print("You chose a new fruit. I hope you enjoy it!")

#EX8
# Write a loop that asks the user to enter pizza toppings one by one.
# Stop the loop when the user types 'quit'.
# For each topping entered, print:
# "Adding [topping] to your pizza."
# After exiting the loop, print all the toppings and the total cost of the pizza.
# The base price is $10, and each topping adds $2.50.

topping_list = []

while True:
  topping = input("Add a topping: ").lower()
  if topping == "quit":
    break
  topping_list.append(topping)
  print(f"Adding {topping} to your pizza.")

print("Pizza base = $10")
print(f"{len(topping_list)} Toppings: {', '.join(topping_list)} -- $2.50 x {len(topping_list)} = ${2.5*len(topping_list)})")
print(f"Total cost is ${((len(topping_list)*2.5)+10)}0")

#EX9
# Ask for the age of each person in a family who wants to buy a movie ticket.
# Calculate the total cost based on the following rules:
# Free for people under 3.
# $10 for people aged 3 to 12.
# $15 for anyone over 12.
# Print the total ticket cost.


family = []
while True:
  member = input('Enter the age of the person or \"quit\" when you are done: ')
  if member == "quit":
    break
  age = int(member)
  if age > 12:
    family.append(15)
  elif 3<=age<=12:
    family.append(10)
  else:
    family.append(0)

print(f"The total cost for {len(family)} ticket(s) is ${sum(family)}")

#EXBonus
# Imagine a group of teenagers wants to see a restricted movie (only for ages 16–21).
# Write a program to:
# Ask for each person’s age.
# Remove anyone who isn’t allowed to watch.
# Print the final list of attendees.

group = []

while True:
  person = input("Please enter the age of the person or \"quit\" when you are done: ")
  if person == "quit":
    break
  age = int(person)
  if 16<=age<=21:
    group.append(age)
print(f"The allowed attendees for the movie are the following ages: {group}")

