# -*- coding: utf-8 -*-
"""Day2_ex_xp_gold.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6DpoCdfM49xG5oeMzIwoKMnLSxPTNVz
"""

#Ex1
# Print the following output in one line of code:

print("Hello world\n"*4+"I love python\n"*4)

#Ex2
# Ask the user to input a month (1 to 12).
# Display the season of the month received :
# Spring runs from March (3) to May (5)
# Summer runs from June (6) to August (8)
# Autumn runs from September (9) to November (11)
# Winter runs from December (12) to February (2)


month = int(input('Write a month of the year in number: '))
if 3<=month<=5:
  print("Spring")
elif 6<=month<=8:
  print("Summer")
elif 9<=month<=11:
  print("Autumn")
elif 1<=month<=2 or month==12:
  print("Winter")
else:
  print('This month does not exist')